using Catalog.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Catalog.Infrastructure.Persistence;

public class CatalogDbContext : DbContext
{
    public CatalogDbContext(DbContextOptions<CatalogDbContext> options) : base(options)
    {
    }

    public DbSet<CatalogItem> CatalogItems => Set<CatalogItem>();

    public DbSet<CatalogBrand> CatalogBrands => Set<CatalogBrand>();

    public DbSet<CatalogType> CatalogTypes => Set<CatalogType>();

    public DbSet<CatalogItemsStock> CatalogItemsStocks => Set<CatalogItemsStock>();

    public DbSet<DiscountItem> DiscountItems => Set<DiscountItem>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        ConfigureCatalogType(builder.Entity<CatalogType>());
        ConfigureCatalogBrand(builder.Entity<CatalogBrand>());
        ConfigureCatalogItem(builder.Entity<CatalogItem>());
        ConfigureCatalogItemsStock(builder.Entity<CatalogItemsStock>());
        ConfigureDiscountItem(builder.Entity<DiscountItem>());

        base.OnModelCreating(builder);
    }

    private static void ConfigureCatalogType(EntityTypeBuilder<CatalogType> builder)
    {
        builder.ToTable("CatalogType");

        builder.HasKey(ct => ct.Id);

        builder.Property(ct => ct.Id)
            .ValueGeneratedOnAdd();

        builder.Property(ct => ct.Type)
            .IsRequired()
            .IsUnicode(false)
            .HasMaxLength(100);
    }

    private static void ConfigureCatalogBrand(EntityTypeBuilder<CatalogBrand> builder)
    {
        builder.ToTable("CatalogBrand");

        builder.HasKey(cb => cb.Id);

        builder.Property(cb => cb.Id)
            .ValueGeneratedOnAdd();

        builder.Property(cb => cb.Brand)
            .IsRequired()
            .IsUnicode(false)
            .HasMaxLength(100);
    }

    private static void ConfigureCatalogItem(EntityTypeBuilder<CatalogItem> builder)
    {
        builder.ToTable("Catalog");

        builder.HasKey(ci => ci.Id);

        // The EF6 model generated ids with a HiLo sequence maintained in application
        // code; identity columns are generated by the database instead.
        builder.Property(ci => ci.Id)
            .ValueGeneratedOnAdd()
            .UseIdentityColumn();

        builder.Property(ci => ci.Name)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(ci => ci.Price)
            .HasPrecision(19, 4)
            .IsRequired();

        builder.Property(ci => ci.PictureFileName)
            .IsRequired();

        builder.Ignore(ci => ci.PictureUri);

        builder.HasOne(ci => ci.CatalogBrand)
            .WithMany()
            .HasForeignKey(ci => ci.CatalogBrandId)
            .IsRequired();

        builder.HasOne(ci => ci.CatalogType)
            .WithMany()
            .HasForeignKey(ci => ci.CatalogTypeId)
            .IsRequired();
    }

    private static void ConfigureCatalogItemsStock(EntityTypeBuilder<CatalogItemsStock> builder)
    {
        builder.ToTable("CatalogItemsStock");

        builder.HasKey(s => s.StockId);

        builder.Property(s => s.StockId)
            .ValueGeneratedOnAdd()
            .UseIdentityColumn();

        builder.Property(s => s.Date)
            .HasColumnType("date");
    }

    private static void ConfigureDiscountItem(EntityTypeBuilder<DiscountItem> builder)
    {
        builder.ToTable("DiscountItem");

        builder.HasKey(d => d.Id);

        builder.Property(d => d.Id)
            .ValueGeneratedOnAdd()
            .UseIdentityColumn();

        builder.Property(d => d.Start)
            .HasColumnType("date");

        builder.Property(d => d.End)
            .HasColumnType("date");
    }
}
