// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopPorted.Models;

namespace eShopPorted.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    partial class CatalogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eShopPorted.Models.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CatalogBrand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Lamborghini"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Porsche"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Maserati"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Other"
                        });
                });

            modelBuilder.Entity("eShopPorted.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableStock");

                    b.Property<int>("CatalogBrandId");

                    b.Property<int>("CatalogTypeId");

                    b.Property<string>("Description");

                    b.Property<int>("MaxStockThreshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("OnReorder");

                    b.Property<string>("PictureFileName")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<int>("RestockThreshold");

                    b.HasKey("Id");

                    b.HasIndex("CatalogBrandId");

                    b.HasIndex("CatalogTypeId");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 100,
                            CatalogBrandId = 1,
                            CatalogTypeId = 1,
                            Description = "Ferrari SF90 Stradale plug-in hybrid supercar with 1000 cv",
                            MaxStockThreshold = 0,
                            Name = "Ferrari SF90 Stradale",
                            OnReorder = false,
                            PictureFileName = "1.png",
                            Price = 507000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 100,
                            CatalogBrandId = 1,
                            CatalogTypeId = 1,
                            Description = "Ferrari 296 GTB with 663 cv V6 hybrid powertrain",
                            MaxStockThreshold = 0,
                            Name = "Ferrari 296 GTB",
                            OnReorder = false,
                            PictureFileName = "2.png",
                            Price = 320000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 100,
                            CatalogBrandId = 1,
                            CatalogTypeId = 2,
                            Description = "Ferrari Roma front-engined V8 grand tourer",
                            MaxStockThreshold = 0,
                            Name = "Ferrari Roma",
                            OnReorder = false,
                            PictureFileName = "3.png",
                            Price = 222000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 100,
                            CatalogBrandId = 1,
                            CatalogTypeId = 3,
                            Description = "Ferrari Purosangue four-door four-seater V12",
                            MaxStockThreshold = 0,
                            Name = "Ferrari Purosangue",
                            OnReorder = false,
                            PictureFileName = "4.png",
                            Price = 390000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 100,
                            CatalogBrandId = 2,
                            CatalogTypeId = 1,
                            Description = "Lamborghini Revuelto V12 hybrid flagship",
                            MaxStockThreshold = 0,
                            Name = "Lamborghini Revuelto",
                            OnReorder = false,
                            PictureFileName = "5.png",
                            Price = 517000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 100,
                            CatalogBrandId = 2,
                            CatalogTypeId = 3,
                            Description = "Lamborghini Urus Performante super SUV",
                            MaxStockThreshold = 0,
                            Name = "Lamborghini Urus Performante",
                            OnReorder = false,
                            PictureFileName = "6.png",
                            Price = 260000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 100,
                            CatalogBrandId = 3,
                            CatalogTypeId = 1,
                            Description = "Porsche 911 GT3 RS track-focused flat-six",
                            MaxStockThreshold = 0,
                            Name = "Porsche 911 GT3 RS",
                            OnReorder = false,
                            PictureFileName = "7.png",
                            Price = 241000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 100,
                            CatalogBrandId = 3,
                            CatalogTypeId = 3,
                            Description = "Porsche Cayenne Turbo GT performance SUV",
                            MaxStockThreshold = 0,
                            Name = "Porsche Cayenne Turbo GT",
                            OnReorder = false,
                            PictureFileName = "8.png",
                            Price = 198000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 100,
                            CatalogBrandId = 4,
                            CatalogTypeId = 1,
                            Description = "Maserati MC20 with Nettuno twin-turbo V6",
                            MaxStockThreshold = 0,
                            Name = "Maserati MC20",
                            OnReorder = false,
                            PictureFileName = "9.png",
                            Price = 240000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 10,
                            AvailableStock = 100,
                            CatalogBrandId = 4,
                            CatalogTypeId = 2,
                            Description = "Maserati GranTurismo Trofeo V6 grand tourer",
                            MaxStockThreshold = 0,
                            Name = "Maserati GranTurismo Trofeo",
                            OnReorder = false,
                            PictureFileName = "10.png",
                            Price = 175000m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 11,
                            AvailableStock = 100,
                            CatalogBrandId = 5,
                            CatalogTypeId = 4,
                            Description = "Carbon ceramic brake kit for track use",
                            MaxStockThreshold = 0,
                            Name = "Carbon Ceramic Brake Kit",
                            OnReorder = false,
                            PictureFileName = "11.png",
                            Price = 12500m,
                            RestockThreshold = 0
                        },
                        new
                        {
                            Id = 12,
                            AvailableStock = 100,
                            CatalogBrandId = 5,
                            CatalogTypeId = 4,
                            Description = "Forged alloy wheel set 20/21 inch staggered",
                            MaxStockThreshold = 0,
                            Name = "Forged Alloy Wheel Set",
                            OnReorder = false,
                            PictureFileName = "12.png",
                            Price = 8900m,
                            RestockThreshold = 0
                        });
                });

            modelBuilder.Entity("eShopPorted.Models.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CatalogType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Sports Car"
                        },
                        new
                        {
                            Id = 2,
                            Type = "GT"
                        },
                        new
                        {
                            Id = 3,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Spare Part"
                        });
                });

            modelBuilder.Entity("eShopPorted.Models.CatalogItem", b =>
                {
                    b.HasOne("eShopPorted.Models.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eShopPorted.Models.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
